apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: env
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://gitea.kubernetes.lan.basmaas.nl/Bas/env
    targetRevision: master
    path: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
