apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: doyoueventrack
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - env: acc
        annotationKey: notifications.argoproj.io/subscribe.on-deployed.drone
        annotationValue: "promote-doyoueventrack-from-acc-to-prd"
      - env: prd
        annotationKey: x
        annotationValue: x
  template:
    metadata:
      name: doyoueventrack-{{ "{{." }}env{{ "}}" }}
      annotations:
        '{{ "{{." }}annotationKey{{ "}}" }}': '{{ "{{." }}annotationValue{{ "}}" }}'
    spec:
      project: default
      source:
        repoURL: https://gitea.kubernetes.lan.basmaas.nl/Bas/env
        targetRevision: master
        path: env/{{ "{{." }}env{{ "}}" }}/doyoueventrack
        helm:
          valueFiles:
            - values.yaml
            - secrets://../../../common/apps/doyoueventrack/values.enc.yaml
            - ../../../common/apps/doyoueventrack/values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ "{{." }}env{{ "}}" }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true