apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: superuser-${NAMESPACE_IMPORT}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: superuser
subjects:
- kind: ServiceAccount
  name: superuser
  namespace: ${NAMESPACE_IMPORT}
